<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Discovery/CapabilityDefinitionTest.php

declare(strict_types=1);

it("happy: attribute class with DefinesCapability auto-discovered under configured path [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: fluent Capability::define registers same CapabilityDefinition shape [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: duplicate name from class and fluent throws at boot [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: ad-hoc invokable without registry is not supported for mutations [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: third discovery path is not registered [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field name when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field description when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field surfaces when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field input when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field output when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field aliases when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field deprecated when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field successor when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field sunset_at when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field groups when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field tags when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field readOnly when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field allowSystemCallers when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field globalSystem when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field approvalPolicy when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field approvalTtlHours when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field rateLimit when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field idempotent when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: definition stores field audit when declared [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: empty surfaces list yields no effective exposure [SURF-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: aliases resolve to canonical name before run [D-012]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: allowSystemCallers empty denies all SystemActors [D-002]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: allowSystemCallers true allows any registered system name [D-002]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: allowSystemCallers list allows only listed SystemActor names [D-002]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: globalSystem true allows SystemActor without tenantId [D-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: readOnly true marks non-mutating for audit and idempotency [D-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: groups and tags available for profile composition [D-008]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: missing name on definition rejected at registration [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: missing input type on mutating capability rejected at registration [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
