<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Support/CapabilityDataTest.php

declare(strict_types=1);

it("happy: fromArray hydrates typed DTO [D-015]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: toArray round trips public props [D-015]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: fromArray rejects unknown keys when additionalProperties false [D-015]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: jsonSchema static generation [D-015]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: rules server-only separate from jsonSchema [D-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
