<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Catalog/DisabledSurfaceCatalogTest.php

declare(strict_types=1);

it("edge: catalog excludes caps only on disabled surface agent [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: catalog still lists caps with other surfaces when agent disabled [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: catalog excludes caps only on disabled surface mcp [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: catalog still lists caps with other surfaces when mcp disabled [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: catalog excludes caps only on disabled surface http [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: catalog still lists caps with other surfaces when http disabled [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: catalog excludes caps only on disabled surface cli [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: catalog still lists caps with other surfaces when cli disabled [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: catalog excludes caps only on disabled surface job [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: catalog still lists caps with other surfaces when job disabled [CAT-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
