package catalog

import "testing"

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. No network by default; mock HTTP.
// See docs/spec.md and AGENTS.md (unit-only, ≥95% coverage when implemented).

func TestCataloglistscapabilitiesfromhttp(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestDescribefetchesjsonschema(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestSchemacachebynameandversion(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestCatalogrefreshinvalidatescache(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestDeprecatedcapabilitywarns(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestCatalognocacheflagforcesrefetch(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestDescribebyaliasresolvescanonical(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestCatalogomitsdisabledsurfaces(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestSchemacacheetaginvalidation(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestCatalogjsonoutputenvelope(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}

func TestSunsetcapabilitywarnedorblocked(t *testing.T) {
	t.Helper()
	t.Skip("TODO: implement unit test with mocks (no live network) [CLI-CAT]")
}
