<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Architecture/NeverDoMatrixTest.php

declare(strict_types=1);

it("fail: messaging must never: call_eloquent_create [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: messaging must never: call_eloquent_update [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: messaging must never: call_eloquent_delete [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: messaging must never: own_run_method [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: messaging must never: bypass_registry_for_tools [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: messaging must never: hard_depend_core_on_messaging [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: messaging must never: embed_capability_input_in_callback [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: messaging must never: approve_without_linked_user [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: messaging must never: trust_telegram_user_id_as_laravel_user [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
