<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Surfaces/JobAdapterTest.php

declare(strict_types=1);

it("happy: RunCapability job payload requires actingAs [D-002]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: RunCapability passes tenantId as first-class field [P2-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: RunCapability refuses tenant magic keys from input for system scope [P2-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: job optional idempotencyKey forwarded [D-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: dispatch without actingAs is not enqueued [D-002]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: failed job tagged with capability name [D-019]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: job handle uses registry not domain action directly [PIPE-008]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: job surface disabled does not register RunCapability helpers [SURF-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
