<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Surfaces/McpAdapterTest.php

declare(strict_types=1);

it("happy: McpToolAdapterV1 registers tools from profile [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: tools call invokes registry with caller mcp and auth profile [D-023]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: tools call does not accept actor from tool JSON [D-023]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: tool input_schema equals catalog input_schema no second schema [D-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: mcp surface disabled registers no tools [SURF-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: mcp progressive disclosure listing still constrained by profile [P2-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: idempotency_key tool arg passed through [D-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: authorization deny through mcp does not mutate [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
