<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Architecture/RefuseTableTest.php

declare(strict_types=1);

it("fail: package refuses anti-pattern: null user allow on jobs [D-002]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: jobs bypass policy global config [D-002]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: tenant magic key for SystemActor [P2-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: client spoofable caller header upgrade [D-022]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: full catalog dump to agents by default [D-008]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: meta tools privilege escape [P2-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: second HTTP invoke controller for CLI [D-009]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: Laravel rules as only schema source [D-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: CLI only validation without server revalidation [D-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: approval without revalidation on accept [D-006]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: unsigned Telegram approve id [D-006]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: approved limbo without resume or atomic [P2-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: silent audit drop when required [D-010]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: peer half-register tools [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: messaging bot runtime inside core [D-007]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: Artisan as product CLI [D-016]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: MCP vague token user without profile [D-023]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: integration credentials without allowlist [D-023]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: actor from tool JSON for MCP [D-023]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: SystemActor can approve [D-006]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: idempotency only on one surface [D-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: dedupe by input without key [D-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: third capability discovery path [D-017]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: domain logic in Go CLI [D-016]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: package refuses anti-pattern: trust exists alone for multi-tenant [D-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
