<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Http/MiddlewareMatrixTest.php

declare(strict_types=1);

it("edge: middleware api can be applied via config [HTTP-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: middleware auth:sanctum can be applied via config [HTTP-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: middleware throttle can be applied via config [HTTP-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: middleware custom can be applied via config [HTTP-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: unauthenticated request blocked when auth middleware on [HTTP-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
