<?php

namespace Rawphp\Capabilities\Discovery;

use RuntimeException;

/**
 * Cached class map for `#[Capability]` discovery (L-015), in the spirit of Laravel's
 * event / package discovery: `capabilities:cache` writes `bootstrap/cache/capabilities.php`,
 * boot uses it instead of walking and tokenizing the discovery path on every request, and
 * `capabilities:clear` removes it. Not a discovery path of its own (D-017) — only a cache of
 * what the attribute scan would find.
 */
final class DiscoveryManifest
{
    public const FILE = 'capabilities.php';

    /**
     * `bootstrap/cache/capabilities.php` for a Laravel application; null when the container has
     * no bootstrap path (bare containers, unit tests) — discovery then always scans.
     */
    public static function pathFor(object $app): ?string
    {
        if (! method_exists($app, 'bootstrapPath')) {
            return null;
        }

        $path = $app->bootstrapPath('cache/'.self::FILE);

        return is_string($path) && $path !== '' ? $path : null;
    }

    /**
     * Class names the attribute scan finds under $paths — what the manifest caches.
     *
     * @param  list<string>  $paths
     * @return list<class-string>
     */
    public static function build(array $paths, ?AttributeDiscoverer $discoverer = null): array
    {
        $classes = [];
        foreach (($discoverer ?? new AttributeDiscoverer)->fromPaths($paths) as $definition) {
            if (is_string($definition->handlerClass) && $definition->handlerClass !== '') {
                $classes[] = $definition->handlerClass;
            }
        }
        $classes = array_values(array_unique($classes));
        sort($classes);

        return $classes;
    }

    /**
     * The cached class map, or null when there is no manifest (scan instead).
     *
     * @return list<class-string>|null
     */
    public static function load(?string $path): ?array
    {
        if ($path === null || ! is_file($path)) {
            return null;
        }

        $data = require $path;
        if (! is_array($data)) {
            return null;
        }

        return array_values(array_filter($data, static fn ($class): bool => is_string($class) && $class !== ''));
    }

    /**
     * @param  list<class-string>  $classes
     */
    public static function write(string $path, array $classes): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! @mkdir($dir, 0755, true) && ! is_dir($dir)) {
            throw new RuntimeException(sprintf('Cannot create manifest directory [%s].', $dir));
        }

        $contents = '<?php'.PHP_EOL.PHP_EOL
            .'// Generated by `php artisan capabilities:cache`; run `capabilities:clear` after adding or removing capabilities.'.PHP_EOL
            .'return '.var_export(array_values($classes), true).';'.PHP_EOL;

        $tmp = $path.'.'.uniqid('', true).'.tmp';
        if (file_put_contents($tmp, $contents) === false || ! rename($tmp, $path)) {
            @unlink($tmp);

            throw new RuntimeException(sprintf('Cannot write manifest [%s].', $path));
        }
    }

    public static function clear(string $path): bool
    {
        return is_file($path) && unlink($path);
    }
}
