<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Registry/LookupMatrixTest.php

declare(strict_types=1);

it("fail: unknown capability via agent is not_found [PIPE-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: known capability wrong surface via agent not invokable as that surface [PIPE-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: known capability correct surface via agent invokable [PIPE-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: unknown capability via mcp is not_found [PIPE-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: known capability wrong surface via mcp not invokable as that surface [PIPE-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: known capability correct surface via mcp invokable [PIPE-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: unknown capability via http is not_found [PIPE-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: known capability wrong surface via http not invokable as that surface [PIPE-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: known capability correct surface via http invokable [PIPE-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: unknown capability via cli is not_found [PIPE-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: known capability wrong surface via cli not invokable as that surface [PIPE-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: known capability correct surface via cli invokable [PIPE-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: unknown capability via job is not_found [PIPE-004]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: known capability wrong surface via job not invokable as that surface [PIPE-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: known capability correct surface via job invokable [PIPE-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
