"""Unit tests for tools/sync_requirements_inventory.py.

Hermetic: temporary directories and fixtures only. Does not mutate monorepo inventory.
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


TOOLS_DIR = Path(__file__).resolve().parents[1]
SYNC_PATH = TOOLS_DIR / "sync_requirements_inventory.py"


def load_sync():
    """Load sync_requirements_inventory as a module without executing main()."""
    spec = importlib.util.spec_from_file_location(
        "sync_requirements_inventory", SYNC_PATH
    )
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules["sync_requirements_inventory"] = mod
    spec.loader.exec_module(mod)
    return mod


class ExtractPestTitlesTests(unittest.TestCase):
    def setUp(self) -> None:
        self.sync = load_sync()

    def test_double_quoted_it_titles(self):
        text = '''
it("happy: stage json_schema_validate fails [PIPE-002]", function () {
    expect(true)->toBeTrue();
});
'''
        titles = self.sync.extract_pest_titles(text)
        self.assertIn(
            "happy: stage json_schema_validate fails [PIPE-002]", titles
        )

    def test_single_quoted_it_titles(self):
        text = """
it('discovers attribute capabilities from configured path into registry', function () {
    expect(true)->toBeTrue();
});
"""
        titles = self.sync.extract_pest_titles(text)
        self.assertIn(
            "discovers attribute capabilities from configured path into registry",
            titles,
        )

    def test_matrix_it_title_variable_from_foreach_string_array(self):
        text = '''
foreach (['agent', 'mcp'] as $caller) {
    it("edge: rate limit applies to caller {$caller} [D-013]", function () use ($caller) {
        expect(true)->toBeTrue();
    });
}
'''
        titles = self.sync.extract_pest_titles(text)
        self.assertIn("edge: rate limit applies to caller agent [D-013]", titles)
        self.assertIn("edge: rate limit applies to caller mcp [D-013]", titles)

    def test_matrix_title_assigned_then_it_variable(self):
        text = '''
$callers = ['agent', 'job'];
foreach ($callers as $caller) {
    $title = "happy: idempotency first for {$caller} [D-005]";
    it($title, function () use ($caller) {
        expect(true)->toBeTrue();
    });
}
'''
        titles = self.sync.extract_pest_titles(text)
        self.assertIn("happy: idempotency first for agent [D-005]", titles)
        self.assertIn("happy: idempotency first for job [D-005]", titles)

    def test_match_arm_static_titles(self):
        text = '''
foreach (['first', 'replay'] as $scenario) {
    $title = match ($scenario) {
        'first' => "happy: idempotency first for agent [D-005]",
        'replay' => "happy: idempotency replay for agent [D-005]",
    };
    it($title, function () use ($scenario) {});
}
'''
        titles = self.sync.extract_pest_titles(text)
        self.assertIn("happy: idempotency first for agent [D-005]", titles)
        self.assertIn("happy: idempotency replay for agent [D-005]", titles)


class ExtractGoTests(unittest.TestCase):
    def setUp(self) -> None:
        self.sync = load_sync()

    def test_go_test_func_names(self):
        text = """
package catalog

func TestCachehitsameversion(t *testing.T) {}
func TestCachemissfetches(t *testing.T) {}
func helper(t *testing.T) {}
"""
        names = self.sync.extract_go_test_names(text)
        self.assertEqual(
            names, {"TestCachehitsameversion", "TestCachemissfetches"}
        )


class SyncInventoryContentTests(unittest.TestCase):
    def setUp(self) -> None:
        self.sync = load_sync()

    def _sample_inventory(self) -> str:
        return """# Requirements inventory → unit test todos

Generated by `tools/generate_requirement_stubs.py`.

**Total TODO cases:** 4

- happy: 2
- fail: 1
- edge: 0
- go: 1

## Core

### `Registry/InvokePipelineTest.php` (2)

- [ ] happy: successful invoke runs full pipeline [PIPE-001]
- [ ] fail: run is not called when stage authorize fails [PIPE-002]

### `Http/RoutesMatrixTest.php` (1)

- [ ] happy: http surface enabled registers list [D-009]

## CLI

### `internal/catalog/cache_test.go` (1)

- [ ] TestCachehitsameversion [CLI-CAT]
"""

    def test_marks_matching_cases_done_and_leaves_gaps(self):
        inv = self._sample_inventory()
        implemented = {
            "happy: successful invoke runs full pipeline [PIPE-001]",
            "TestCachehitsameversion",
        }
        out = self.sync.sync_inventory_content(inv, implemented)
        self.assertIn(
            "- [x] happy: successful invoke runs full pipeline [PIPE-001]", out
        )
        self.assertIn("- [x] TestCachehitsameversion [CLI-CAT]", out)
        self.assertIn(
            "- [ ] fail: run is not called when stage authorize fails [PIPE-002]",
            out,
        )
        self.assertIn(
            "- [ ] happy: http surface enabled registers list [D-009]", out
        )

    def test_header_reports_implemented_vs_remaining(self):
        inv = self._sample_inventory()
        implemented = {
            "happy: successful invoke runs full pipeline [PIPE-001]",
            "TestCachehitsameversion",
        }
        out = self.sync.sync_inventory_content(inv, implemented)
        self.assertNotIn("**Total TODO cases:**", out)
        # 2 implemented, 2 remaining of 4
        self.assertRegex(
            out,
            r"\*\*.*(?:implemented|Implemented).*(?:remaining|Remaining).*\*\*",
        )
        self.assertIn("2", out)
        self.assertIn("4", out)

    def test_idempotent_rerun(self):
        inv = self._sample_inventory()
        implemented = {
            "happy: successful invoke runs full pipeline [PIPE-001]",
            "TestCachehitsameversion",
        }
        once = self.sync.sync_inventory_content(inv, implemented)
        twice = self.sync.sync_inventory_content(once, implemented)
        self.assertEqual(once, twice)

    def test_go_inventory_line_matches_test_name_without_suffix(self):
        inv = "- [ ] TestDocandcodeagreeValidationFailedExit2 [D-018]\n"
        out = self.sync.sync_inventory_content(
            inv, {"TestDocandcodeagreeValidationFailedExit2"}
        )
        self.assertIn(
            "- [x] TestDocandcodeagreeValidationFailedExit2 [D-018]", out
        )


class CollectImplementedFromTreeTests(unittest.TestCase):
    def setUp(self) -> None:
        self.sync = load_sync()

    def test_collects_php_and_go_from_package_tree(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            php = (
                root
                / "packages/laravel-capabilities/tests/Unit/Registry/FooTest.php"
            )
            php.parent.mkdir(parents=True)
            php.write_text(
                '<?php\nit("happy: pipeline ok [PIPE-001]", function () {});\n'
                "it('single quoted case', function () {});\n"
                "foreach (['agent'] as $caller) {\n"
                '    it("edge: for {$caller}", function () use ($caller) {});\n'
                "}\n",
                encoding="utf-8",
            )
            go = root / "packages/capabilities-cli/internal/catalog/cache_test.go"
            go.parent.mkdir(parents=True)
            go.write_text(
                "package catalog\n\nfunc TestCachehitsameversion(t *testing.T) {}\n",
                encoding="utf-8",
            )
            titles = self.sync.collect_implemented_titles(root)
            self.assertIn("happy: pipeline ok [PIPE-001]", titles)
            self.assertIn("single quoted case", titles)
            self.assertIn("edge: for agent", titles)
            self.assertIn("TestCachehitsameversion", titles)


class SyncInventoryFileTests(unittest.TestCase):
    def setUp(self) -> None:
        self.sync = load_sync()

    def test_sync_file_writes_updated_inventory(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            inv = root / "docs/requirements-inventory.md"
            inv.parent.mkdir(parents=True)
            inv.write_text(
                "# Inv\n\n**Total TODO cases:** 1\n\n"
                "- [ ] happy: known case [X]\n"
                "- [ ] happy: missing case [Y]\n",
                encoding="utf-8",
            )
            php = (
                root
                / "packages/laravel-capabilities/tests/Unit/XTest.php"
            )
            php.parent.mkdir(parents=True)
            php.write_text(
                '<?php\nit("happy: known case [X]", function () {});\n',
                encoding="utf-8",
            )
            stats = self.sync.sync_inventory_file(root)
            text = inv.read_text(encoding="utf-8")
            self.assertIn("- [x] happy: known case [X]", text)
            self.assertIn("- [ ] happy: missing case [Y]", text)
            self.assertNotIn("**Total TODO cases:**", text)
            self.assertEqual(stats["implemented"], 1)
            self.assertEqual(stats["remaining"], 1)
            self.assertEqual(stats["total"], 2)


if __name__ == "__main__":
    unittest.main()
