<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: TestingHelpers/ParityAndSnapshotsTest.php

declare(strict_types=1);

it("happy: assertSchemaSnapshot fails when input_schema changes without update [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: assertSchemaSnapshot passes when schema matches snapshot [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: assertParity same success class across registry surfaces with mocks [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: assertCannotInvokeAcrossTenant fails test on cross-tenant success [D-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: assertScopeResolvedTo fails when scope mismatches (case 1) [D-003]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: assertLastScopeTenant reflects SystemActor first-class tenant not smuggled input [P2-005]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: assertParity same deny class across registry http and ai with mocks [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: assertParity can include surface path for agent [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: assertParity can include surface path for mcp [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: assertParity can include surface path for http [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: assertParity can include surface path for cli [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: assertParity can include surface path for job [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: Capability::fake available for unit tests [D-020]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
