<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: RateLimiting/RateLimitingTest.php

declare(strict_types=1);

it("happy: under limit invoke succeeds [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: exceeding per_minute returns rate_limited [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: exceeding per_capability_per_minute returns rate_limited [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: agent turn max_tool_calls stops loop with structured message [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: per-capability rateLimit attribute overrides defaults [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: rate limit keys include actor capability surface tenant [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: rate limits disabled when config enabled false [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: rate limit applies to caller agent [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: exceeding limit for caller agent does not call run [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: rate limit applies to caller mcp [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: exceeding limit for caller mcp does not call run [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: rate limit applies to caller http [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: exceeding limit for caller http does not call run [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: rate limit applies to caller cli [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: exceeding limit for caller cli does not call run [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: rate limit applies to caller job [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: exceeding limit for caller job does not call run [D-013]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: rate_limited maps to HTTP 429 and CLI exit 6 [D-018]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
