<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Adapters/PeerAdaptersTest.php

declare(strict_types=1);

it("happy: AdapterApi CURRENT is V1 [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: AiToolAdapter supportsInstalledPeer false when package missing [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: McpToolAdapter supportsInstalledPeer false when package missing [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: PeerVersionProbe feature-detects installed peer [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: boot fail when surface enabled require_package and peer missing [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: boot disable surface when on_incompatible disable [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: tool schema mapping unit maps capability JSON Schema to peer tool fields via mock peer [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: invoke round-trip mock peer tool call to registry result shape [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: profile filter still applies through adapter [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: authorization deny through adapter does not mutate [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: idempotency key passed through adapter when present [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: unsupported peer version does not half-register tools [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: catch-all swallow of adapter errors leading to empty tools is refused [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("happy: AdapterApi bump required when bridge call shapes change [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("edge: health reports disabled_incompatible when soft-disabled [D-011]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
