<?php

// AUTO-GENERATED by tools/generate_requirement_stubs.py — do not edit by hand.
// Spec-derived unit test stubs. Unit-only, no database — see AGENTS.md.
// Package file: Context/BuildFailurePointsTest.php

declare(strict_types=1);

it("fail: context build refuses null_actor [CTX-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: context build refuses unknown_caller [CTX-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: context build refuses missing_scope_when_required [CTX-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: context build refuses invalid_mcp_auth_profile [CTX-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();

it("fail: context build refuses missing_job_acting_as_metadata [CTX-001]", function () {
    // TODO: implement unit test with mocks/fakes (no DB).
})->todo();
